// No database yet. Each listing below only has one real photo from
// ListingClient's data, so the gallery repeats that single image to
// stand in for a fuller set. Swap this whole file for a real fetch

import { Property } from "./types/property";

// (by id) once listings are wired up to storage.
function buildGallery(imageSrc: string, count = 6): string[] {
  return Array.from({ length: count }, () => imageSrc);
}

// Placeholder until each listing carries its own agent. All 12 mock
// listings point at this one agent for now.
const DEFAULT_AGENT = {
  id: "a1",
  name: "Sarah Jenkins",
  avatarUrl: "/home.jpg",
  phone: "+2348012345678",
  email: "sarah.jenkins@example.com",
};

export const MOCK_PROPERTIES: Property[] = [
  // Homes
  {
    id: "home-1",
    title: "4 Bedroom Duplex with BQ",
    status: "For Sale",
    daysAgo: "418d ago",
    views: 128,
    likes: 16,
    price: "₦185,000,000",
    beds: 4,
    baths: 4,
    area: "100 sqft",
    location: "Worji, Port Harcourt, Rivers",
    propertyType: "home",
    about: [
      "A spacious 4 bedroom duplex with a boys' quarters, built for comfortable family living in Worji, Port Harcourt.",
      "Reach out to the listing agent for a viewing and full details on finishing and title documents.",
    ],
    images: buildGallery("/home.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "home-2",
    title: "Luxury Serviced Apartment",
    status: "For Rent",
    daysAgo: "404d ago",
    views: 119,
    likes: 13,
    price: "₦22,000,000",
    beds: 4,
    baths: 4,
    area: "N/A sqft",
    location: "Abuja, Federal Capital Territory",
    propertyType: "home",
    about: [
      "A fully serviced 4 bedroom apartment in Abuja, available for rent with round the clock power and security.",
      "Contact the agent to arrange a viewing or ask about the lease terms.",
    ],
    images: buildGallery("/home2.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "home-3",
    title: "Furnished 4 Bedroom Duplex",
    status: "For Sale",
    daysAgo: "117d ago",
    views: 46,
    likes: 7,
    price: "₦480,000,000",
    beds: 4,
    baths: 4,
    area: "100 sqft",
    location: "Peter Odili Road, Port-Harcourt, Rivers State",
    propertyType: "home",
    about: [
      "A fully furnished 4 bedroom duplex on Peter Odili Road, ready for immediate move-in.",
      "Reach out to the listing agent for a walkthrough and pricing breakdown.",
    ],
    images: buildGallery("/home3.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "home-4",
    title: "Exquisitely Built 4 Bedroom Duplex",
    status: "For Sale",
    daysAgo: "99d ago",
    views: 46,
    likes: 5,
    price: "₦280,000,000",
    beds: 4,
    baths: 4,
    area: "470 sqft",
    location: "Sars Road, Alozo, Rivers State",
    propertyType: "home",
    about: [
      "A well finished 4 bedroom duplex on Sars Road, Alozo, with generous compound space.",
      "Contact the agent for more photos and to schedule a visit.",
    ],
    images: buildGallery("/home4.jpg"),
    agent: DEFAULT_AGENT,
  },

  // Estates
  {
    id: "estate-2",
    title: "Crown Heights Residency",
    status: "New Phase",
    daysAgo: "25d ago",
    views: 280,
    likes: 31,
    price: "₦500,000,000",
    unitsAvailable: 8,
    area: "12,000 sqft",
    location: "Maitama, Abuja, FCT",
    propertyType: "estate",
    about: [
      "Crown Heights Residency is a new phase release in Maitama, Abuja, with 8 units currently available.",
      "Contact the agent for the unit floor plans and payment plan options.",
    ],
    images: buildGallery("/es2.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "estate-3",
    title: "Oakwood Gardens & Smart Villas",
    status: "For Sale",
    daysAgo: "45d ago",
    views: 195,
    likes: 24,
    price: "₦280,000,000",
    unitsAvailable: 20,
    area: "8,500 sqft",
    location: "Peter Odili Road, Port Harcourt, Rivers",
    propertyType: "estate",
    about: [
      "Oakwood Gardens & Smart Villas offers 20 available units on Peter Odili Road, Port Harcourt.",
      "Reach out to the agent for smart home features and current unit availability.",
    ],
    images: buildGallery("/es3.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "estate-4",
    title: "Oakwood Gardens & Smart Villas",
    status: "For Sale",
    daysAgo: "45d ago",
    views: 195,
    likes: 24,
    price: "₦280,000,000",
    unitsAvailable: 20,
    area: "8,500 sqft",
    location: "Peter Odili Road, Port Harcourt, Rivers",
    propertyType: "estate",
    about: [
      "Oakwood Gardens & Smart Villas offers 20 available units on Peter Odili Road, Port Harcourt.",
      "Reach out to the agent for smart home features and current unit availability.",
    ],
    images: buildGallery("/es4.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "estate-5",
    title: "The Haven Waterfront Estates",
    status: "Selling Fast",
    daysAgo: "60d ago",
    views: 410,
    likes: 58,
    price: "₦420,000,000",
    unitsAvailable: 5,
    area: "10,000 sqft",
    location: "Ikoyi, Lagos State",
    propertyType: "estate",
    about: [
      "The Haven Waterfront Estates in Ikoyi is selling fast, with only 5 units left.",
      "Contact the agent today to secure a unit before the phase closes.",
    ],
    images: buildGallery("/es5.jpg"),
    agent: DEFAULT_AGENT,
  },

  // Land
  {
    id: "land-1",
    title: "A Large 179 Hectares of Land Available",
    status: "For Sale",
    daysAgo: "154d ago",
    views: 14,
    likes: 3,
    price: "₦6,000,000",
    plots: 1,
    area: "179 sqft",
    location: "Isiokpo II, Isiokpo, Rivers",
    propertyType: "land",
    about: [
      "A large plot of land in Isiokpo II, suitable for residential or agricultural development.",
      "Contact the agent for the survey plan and title documents.",
    ],
    images: buildGallery("/lan1.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "land-2",
    title: "Dry Commercial Land Facing Express",
    status: "For Sale",
    daysAgo: "80d ago",
    views: 95,
    likes: 12,
    price: "₦15,000,000",
    plots: 2,
    area: "900 sqft",
    location: "Greater Port Harcourt, Rivers",
    propertyType: "land",
    about: [
      "Dry commercial land facing the expressway in Greater Port Harcourt, ideal for retail or office development.",
      "Contact the agent for zoning details and access road documentation.",
    ],
    images: buildGallery("/lan2.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "land-3",
    title: "Prime Residential Layout Plots",
    status: "Selling Fast",
    daysAgo: "40d ago",
    views: 142,
    likes: 18,
    price: "₦35,000,000",
    plots: 4,
    area: "1,800 sqft",
    location: "Airport Road, Port Harcourt, Rivers",
    propertyType: "land",
    about: [
      "Prime residential layout plots on Airport Road, Port Harcourt, selling fast within a gated layout.",
      "Contact the agent to reserve a plot before the current phase sells out.",
    ],
    images: buildGallery("/lan3.jpg"),
    agent: DEFAULT_AGENT,
  },
  {
    id: "land-4",
    title: "10 Plots of Fenced Dry Land with C of O",
    status: "For Sale",
    daysAgo: "12d ago",
    views: 210,
    likes: 29,
    price: "₦85,000,000",
    plots: 10,
    area: "5,000 sqft",
    location: "Eneka, Port Harcourt, Rivers State",
    propertyType: "land",
    about: [
      "10 fenced plots of dry land in Eneka, Port Harcourt, sold with a Certificate of Occupancy.",
      "Contact the agent for the C of O documents and site inspection.",
    ],
    images: buildGallery("/lan4.jpg"),
    agent: DEFAULT_AGENT,
  },
];

export function getPropertyById(id: string): Property | undefined {
  return MOCK_PROPERTIES.find((property) => property.id === id);
}
